Run one tool per engine for remotehost
- engine naming needs to be resolved to allow multiple remotehost
  endpoints

diff --git a/endpoints/remotehost/remotehost b/endpoints/remotehost/remotehost
--- a/endpoints/remotehost/remotehost
+++ b/endpoints/remotehost/remotehost
@@ -47,6 +47,7 @@ image_cache_size=3
 osruntime[default]="chroot"
 host_mounts=""
 hypervisor_host="none" # Default is no hypervisor
+new_remotehost_followers=""
 
 function endpoint_remotehost_engine_init() {
     echo "Running endpoint_engine_init"
@@ -159,6 +160,18 @@ function cleanup_osruntime() {
     echo "All podman container mounts:"
     do_ssh $user@$host podman mount
     echo
+
+    # Clean up tool engines
+
+    echo "Going to remove a pod for each tool"
+    local tools=`awk -F: '{print $1}' $config_dir/tool-cmds/profiler/start`
+    tool_count=1
+    for tool in $tools; do
+        engine_label=profiler-$tool_count
+        container_name="${endpoint_label}_${run_id}_${engine_label}_${os_runtime}"
+        do_ssh $user@$host podman rm ${container_name}
+        let tool_count=$tool_count+1
+    done
 
     for this_cs_label in ${clients[@]} ${servers[@]} ${collectors[@]}; do
         set_osruntime_numanode_cpupart ${this_cs_label}
@@ -282,6 +295,70 @@ function remotehost_req_check() {
     fi
 }
 
+function exec_pod() {
+        local engine_label=$1; shift
+        local tool=""
+        tool=$1; shift
+        local os_runtime="pod"
+
+        env_tool_file="${engine_label}_env.txt"
+        get_image profiler $tool_count this_image
+
+        echo "rickshaw_host=$controller_ipaddr"         >> ${endpoint_run_dir}/${env_tool_file}
+        echo "endpoint_run_dir=$endpoint_run_dir"       >> ${endpoint_run_dir}/${env_tool_file}
+        echo "cs_label=$engine_label"                   >> ${endpoint_run_dir}/${env_tool_file}
+        echo "tool_name=$tool"                          >> ${endpoint_run_dir}/${env_tool_file}
+        echo "base_run_dir=$base_run_dir"               >> ${endpoint_run_dir}/${env_tool_file}
+        echo "endpoint=remotehost"                      >> ${endpoint_run_dir}/${env_tool_file}
+        echo "max_rb_attempts=$max_rb_attempts"         >> ${endpoint_run_dir}/${env_tool_file}
+        echo "ssh_id=${ssh_id}"                         >> ${endpoint_run_dir}/${env_tool_file}
+
+        # roadblock opts like redis server
+        for cs_rb_opt in $cs_rb_opts; do
+            arg=$(echo $cs_rb_opt | awk -F'=' '{print $1}')
+            value=$(echo $cs_rb_opt | awk -F'=' '{print $2}')
+            arg=$(echo ${arg} | sed -e 's/^--//' -e 's/-/_/g' )
+            echo "${arg}=${value}"                      >> ${endpoint_run_dir}/${env_tool_file}
+        done
+
+        if pushd ${endpoint_run_dir} >/dev/null; then
+            echo "Copying ${endpoint_run_dir}/${env_tool_file} to ${user}@${host}:${remote_cfg_dir}"
+            do_scp "" "${env_tool_file}" "${user}@${host}" "${remote_cfg_dir}"
+            popd >/dev/null
+        else
+            echo "Failed to pushd to ${endpoint_run_dir} to scp env file"
+            exit 1
+        fi
+
+        tool_cs_cmd="podman run"
+        tool_cs_cmd+=" --detach=true"
+        tool_cs_cmd+=" --name=${endpoint_label}_${run_id}_${engine_label}_podman"
+        tool_cs_cmd+=" --env-file ${remote_cfg_dir}/${env_tool_file}"
+        tool_cs_cmd+=" --privileged --ipc=host --pid=host --net=host --security-opt=label=disable"
+        tool_cs_cmd+=" --mount=type=bind,source=${remote_data_dir},destination=/tmp"
+        tool_cs_cmd+=" --mount=type=bind,source=/lib/firmware,destination=/lib/firmware"
+        tool_cs_cmd+=" --mount=type=bind,source=/lib/modules,destination=/lib/modules"
+        tool_cs_cmd+=" --mount=type=bind,source=/usr/src,destination=/usr/src"
+        if [ "$host_mounts" != "" ]; then
+            local oldIFS=$IFS
+            IFS=" "
+            for fs in $host_mounts; do
+            tool_cs_cmd+=" --mount=type=bind,source=$fs,destination=$fs"
+            done
+            IFS=$oldIFS
+        fi
+        tool_cs_cmd+=" ${this_image}"
+
+        echo -e "About to run:\ndo_ssh $user@$host ${tool_cs_cmd}\n"
+        # Note: this never really captures non-zero exits
+        do_ssh $user@$host "${tool_cs_cmd}"
+        ssh_rc=$?
+        if [ ${ssh_rc} -gt 0 ]; then
+            echo "running ${os_runtime} failed"
+            exit 1
+        fi
+}
+
 function launch_osruntime() {
     local this_cs_label this_cs_log_file base_cmd cs_cmd cs_rb_env env_file
     local env_opts existing_container container_id container_mount container_name fs
@@ -304,29 +381,39 @@ function launch_osruntime() {
 
     set_total_cpupart
 
+    # Launch the tool engines (support only pods)
+    local tools=`awk -F: '{print $1}' $config_dir/tool-cmds/profiler/start`
+    echo "Creating a pod for each of these tools: $tools"
+    tool_count=1
+    echo "Going to create a pod for each tool"
+    for tool in $tools; do
+        # This label will not work with mulitple remotehost endpoints!
+        engine_label=profiler-$tool_count
+        exec_pod $engine_label $tool
+        new_remotehost_followers+=" $engine_label"
+        let tool_count=$tool_count+1
+    done
+
     # For each client and server launch the actual script which will run it.
     count=1
+    ssh_id=$(sed -z 's/\n/\\n/g' ${config_dir}/rickshaw_id.rsa)
     for this_cs_label in ${clients[@]} ${servers[@]} ${collectors[@]}; do
+
         this_cs_type=`echo $this_cs_label | awk -F- '{print $1}'`
         this_cs_id=`echo $this_cs_label | awk -F- '{print $2}'`
         get_image $this_cs_type $this_cs_id this_image
         set_osruntime_numanode_cpupart $this_cs_label
 
+        echo "Preparing to launch $this_cs_label"
         container_name="${endpoint_label}_${run_id}_${this_cs_label}_${os_runtime}"
         existing_container=`do_ssh $user@$host podman ps --all --format "{{.Names}}" | grep ^$container_name$`
         if [ ! -z "$existing_container" ]; then
             echo "WARNING: found existing container '$existing_container', deleting"
+            do_ssh $user@$host podman stop $container_name
+            do_ssh $user@$host podman kill $container_name
             do_ssh $user@$host podman rm $container_name
         fi
         this_cs_log_file="$this_cs_label.txt"
-
-        if [ $count -gt 1 ]; then
-            # Only the first client/server needs to run tools
-            echo "Skipping tools execution on $this_cs_label because a previous client/server is running tools on this host"
-            this_disable_tools="1"
-        else
-            this_disable_tools="$disable_tools"
-        fi
 
         if [ "${os_runtime}" == "chroot" ]; then
             echo "using chroot"
@@ -387,7 +474,8 @@ function launch_osruntime() {
             base_cmd+=" --cpu-partition-index=${count}"
             base_cmd+=" --cpu-partitioning=$cpu_partitioning"
             base_cmd+=" --engine-script-start-timeout=$engine_script_start_timeout"
-            base_cmd+=" --disable-tools=$this_disable_tools"
+            # For one-tool-per-engine, client and server engines never run tools
+            base_cmd+=" --disable-tools=1"
             if [ $numa_node -gt -1 ]; then
                 base_cmd="numactl -N $numa_node -m $numa_node $base_cmd"
             fi
@@ -413,7 +501,9 @@ function launch_osruntime() {
             echo "max_rb_attempts=$max_rb_attempts"         >> ${endpoint_run_dir}/${env_file}
             echo "ssh_id=${ssh_id}"                         >> ${endpoint_run_dir}/${env_file}
             echo "engine_script_start_timeout=${engine_script_start_timeout}" >> ${endpoint_run_dir}/${env_file}
-            echo "disable_tools=$this_disable_tools"        >> ${endpoint_run_dir}/${env_file}
+
+            # For one-tool-per-engine, client and server engines never run tools
+            echo "disable_tools=1"        >> ${endpoint_run_dir}/${env_file}
 
             for cs_rb_opt in $cs_rb_opts; do
                 arg=$(echo $cs_rb_opt | awk -F'=' '{print $1}')
@@ -458,7 +548,7 @@ function launch_osruntime() {
             cs_cmd+=" ${this_image}"
         fi
 
-        echo -e "About to run:\n${cs_cmd}\n"
+        echo -e "About to run:\ndo_ssh $user@$host ${cs_cmd}\n"
         do_ssh $user@$host "${cs_cmd}"
         ssh_rc=$?
         if [ ${ssh_rc} -gt 0 ]; then
@@ -558,4 +648,5 @@ fi
 ssh_id=$(sed -z 's/\n/\\n/g' ${config_dir}/rickshaw_id.rsa)
 base_req_check
 launch_osruntime
-process_roadblocks remotehost
+echo "about to call: process_roadblocks remotehost $new_remotehost_followers"
+process_roadblocks remotehost $new_remotehost_followers
